version: "3.3"
services:

## Router
  router01:
    image: mongo
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr:27017 --bind_ip_all
    ports:
      - 27117:27017
    volumes:
      - ./scripts:/scripts

## Config Server
  configsvr:
    image: mongo
    container_name: mongo-config-server
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts 
    ports:
      - 27119:27017
    links:
      - shard01-a
      - shard02-a
      - shard03-a

## Shards
  ## Shards 01
   
  shard01-a:
    image: mongo
    container_name: shard-01-rs-a
    command: mongod --port 27017 --shardsvr --replSet shard-01-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27122:27017
    links:
      - shard01-b
      - shard01-c
      - shard01-d
  shard01-b:
    image: mongo
    container_name: shard-01-rs-b
    command: mongod --port 27017 --shardsvr --replSet shard-01-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27123:27017
  shard01-c:
    image: mongo
    container_name: shard-01-rs-c
    command: mongod --port 27017 --shardsvr --replSet shard-01-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27124:27017
  shard01-d:
    image: mongo
    container_name: shard-01-rs-d
    command: mongod --port 27017 --shardsvr --replSet shard-01-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27131:27017

  ## Shards 02
  shard02-a:
    image: mongo
    container_name: shard-02-rs-a
    command: mongod --port 27017 --shardsvr --replSet shard-02-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27125:27017
    links:
      - shard02-b
      - shard02-c
      - shard02-d
  shard02-b:
    image: mongo
    container_name: shard-02-rs-b
    command: mongod --port 27017 --shardsvr --replSet shard-02-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27126:27017
  shard02-c:
    image: mongo
    container_name: shard-02-rs-c
    command: mongod --port 27017 --shardsvr --replSet shard-02-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27127:27017
  shard02-d:
    image: mongo
    container_name: shard-02-rs-d
    command: mongod --port 27017 --shardsvr --replSet shard-02-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27132:27017

  ## Shards 03
  shard03-a:
    image: mongo
    container_name: shard-03-rs-a
    command: mongod --port 27017 --shardsvr --replSet shard-03-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27128:27017
    links:
      - shard03-b
      - shard03-c
      - shard03-d
  shard03-b:
    image: mongo
    container_name: shard-03-rs-b
    command: mongod --port 27017 --shardsvr --replSet shard-03-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27129:27017
  shard03-c:
    image: mongo
    container_name: shard-03-rs-c
    command: mongod --port 27017 --shardsvr --replSet shard-03-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27130:27017
  shard03-d:
    image: mongo
    container_name: shard-03-rs-d
    command: mongod --port 27017 --shardsvr --replSet shard-03-rs
    volumes:
      - ./scripts:/scripts
    ports:
      - 27133:27017
